fsl:
	vcs ../mapped/fixSinkList_mapped.v ../lib/saed90nm.v ../rtl/memory.v tb_fixSinkList.v -full64 -debug_pp +neg_tchk -R -l vcs.log

nsioc:
	vcs ../mapped/neighborSinkInOtherCluster_mapped.v ../lib/saed90nm.v ../rtl/memory.v tb_neighborSinkInOtherCluster.v -full64 -debug_pp +neg_tchk -R -l vcs.log

fmb:
	vcs ../mapped/findMyBest_mapped.v ../lib/saed90nm.v ../rtl/memory.v tb_findMyBest.v -full64 -debug_pp +neg_tchk -R -l vcs.log

bnimc:
	vcs ../mapped/betterNeighborsInMyCluster_mapped.v ../lib/saed90nm.v ../rtl/memory.v tb_betterNeighborsInMyCluster.v -full64 -debug_pp +neg_tchk -R -l vcs.log

ufsl:
	vcs ../rtl/fixSinkList.v ../lib/saed90nm.v ../rtl/memory.v tb_fixSinkList.v -full64 -debug_pp +neg_tchk -R -l vcs.log

unsioc:
	vcs ../rtl/neighborSinkInOtherCluster.v ../lib/saed90nm.v ../rtl/memory.v tb_neighborSinkInOtherCluster.v -full64 -debug_pp +neg_tchk -R -l vcs.log

ufmb:
	vcs ../rtl/findMyBest.v ../lib/saed90nm.v ../rtl/memory.v tb_findMyBest.v -full64 -debug_pp +neg_tchk -R -l vcs.log

ubnimc:
	vcs ../rtl/betterNeighborsInMyCluster.v ../lib/saed90nm.v ../rtl/memory.v tb_betterNeighborsInMyCluster.v -full64 -debug_pp +neg_tchk -R -l vcs.log

