fsl:
	dc_shell -f fixSinkList.tcl -output_log_file compile.log

nsioc:
	dc_shell -f neighborSinkInOtherCluster.tcl -output_log_file compile.log

fmb:
	dc_shell -f findMyBest.tcl -output_log_file compile.log

bnimc:
	dc_shell -f betterNeighborsInMyCluster.tcl -output_log_file compile.log

m1:
	dc_shell -f mux_1bit.tcl -output_log_file compile.log

m11:
	dc_shell -f mux_11bit.tcl -output_log_file compile.log

m16:
	dc_shell -f mux_16bit.tcl -output_log_file compile.log

	
