fsl:
	dc_shell -f fixSinkList.tcl -output_log_file fixSinkList.log

nsioc:
	dc_shell -f neighborSinkInOtherCluster.tcl -output_log_file neighborSinkInOtherCluster.log

fmb:
	dc_shell -f findMyBest.tcl -output_log_file findMyBest.log

bnimc:
	dc_shell -f betterNeighborsInMyCluster.tcl -output_log_file betterNeighborsInMyCluster.log

m1:
	dc_shell -f mux_1bit.tcl -output_log_file mux_1bit.log

m11:
	dc_shell -f mux_11bit.tcl -output_log_file mux_11bit.log

m16:
	dc_shell -f mux_16bit.tcl -output_log_file mux_16bit.log
	
wp: 
	dc_shell -f winnerPolicy.tcl -output_log_file winnerPolicy.log

rng:
	dc_shell -f randomGenerator.tcl -output_log_file randomGenerator.log

rnga:
	dc_shell -f rngAddress.tcl -output_log_file rngAddress.log

r:
	dc_shell -f reward.tcl -output_log_file reward.log

lc:
	dc_shell -f learnCosts.tcl -output_log_file learnCosts.log

s:
	dc_shell -f selectMyAction.tcl -output_log_file selectMyAction.log

fsl:
	dc_shell -f fixSinkList.tcl -output_log_file fixSinkList.log